services:
  - type: web
    name: erp-yusung-api
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn app.main:app --app-dir backend --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PROJECT_NAME
        value: "ERP Yusung API"
      - key: SECRET_KEY
        generateValue: true
      - key: POSTGRES_SERVER
        sync: false
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false
